name: svalinn

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - feature/deployment
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Build
        run: bash ci/build.sh

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: bash ci/build.sh

      - name: Upload Release Assets
        id: upload-release-assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.get_release.outputs.id }}
          assets_path: ./*/build/outputs/aar/*.aar

